# This is a config file to create EKS cluster using eksctl

apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: devops-cluster
  region: us-east-2

nodeGroups:
  - name: devops-ng
    instanceType: m5.large
    desiredCapacity: 2