apiVersion: v1
kind: Service
metadata:
  name: devops-capstone-service
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone-deployment
spec:
  selector:
    matchLabels:
      app: capstone-app
  replicas: 1
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
        - name: devops-capstone
          image: ademola/devops-capstone:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: "/"
              port: 80
              initialDelaySeconds: 5
              periodSeconds: 5
              successThreshold: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  minReadySeconds: 10