# This script grants additional AWS users or roles to interact with the cluster

apiVersion: v1 
kind: ConfigMap 
metadata: 
  name: aws-auth 
  namespace: kube-system 
data: 
  mapRoles: | 
    - rolearn: arn:aws:iam::020483229178:role/eks-cluster-WorkerNodeRole-16F0JJAQBX9MC
      username: system:node:{{EC2PrivateDNSName}} 
      groups: 
        - system:bootstrappers 
        - system:nodes 
